export const dummyMessages = [
  { id: "1", text: "111", isUser: true, username: "You", timestamp: "09:00" },
  {
    id: "2",
    text: "222s2",
    isUser: true,
    username: "You",
    timestamp: "09:01",
  },
  {
    id: "3",
    text: "444",
    isUser: false,
    username: "John",
    timestamp: "09:02",
  },
  {
    id: "4",
    text: "555",
    isUser: false,
    username: "John",
    timestamp: "09:03",
  },
  {
    id: "5",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "6",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "7",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "8",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "9",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "11",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "112",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "113",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "114",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
  {
    id: "121",
    text: "666",
    isUser: false,
    username: "John",
    timestamp: "09:04",
  },
];
